language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install pipenv"
  - "pipenv install --dev --skip-lock"
script:
  - "make test"
  - "make lint"
  - "make check-fmt"
  - "gunicorn --check-config app.main:APP"
after_success:
  - coveralls
